POST http://localhost:3000/
Content-Type: application/json

{
  "user": {
    "firstName": "Sourav",
    "lastName": "Sarkar"
  }
}

### text sending
POST http://localhost:3000/
Content-Type: text/plain

Hello Sourav

### url encoded
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

name=Sourav&role=Admin



### nested url encoded
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

name=Sourav&address[city]=Kolkata&address[country]=India

### url encoded username password
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

username=sourav&email=sourav@example.com&password=123456

### json for db
### Create User
POST http://localhost:3000/
Content-Type: application/json

{
  "name": "Sourav",
  "age": 25,
  "email": "sourav@example.com",
  "password": "secret123"
}

### Create Users api
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Cytherea",
  "age": 35,
  "email": "sardar@example.com",
  "password": "secret123"
}


### get all users
GET http://localhost:3000/api/users

### get single id
GET http://localhost:3000/api/users/4


### update users using put
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "name": "Captain Jack sparrow",
  "age": 25,
  "is_active": false,
  "password": "lola123"
}

### null safe test for update
PUT http://localhost:3000/api/users/7
Content-Type: application/json

{
  "age": 27
}

### delete user 
DELETE http://localhost:3000/api/users/7